In [1]:
import numpy as np

In [4]:
%%time
#if you write the previous line in your cell, it prints you the next execution time

##generate a list of numbers [0:10000]
a = list(range(100000))
b = list(range(100000))

Wall time: 5 ms


In [5]:
%%time

#we do some operations between the two lines
# c = a+ 2 *b
for _ in range(10):
    c = []
    for i in range(len(a)):
        c.append(a[i] + 2 * b[i])

Wall time: 349 ms


In [6]:
%%time 

x = np.arange(100000)
y = np.arange(100000)

Wall time: 999 µs


In [7]:
%%time
for _ in range(10):
    z = x + 2 * y

Wall time: 4 ms


In [8]:
list_eter = ["asd", 3, True]
type(list_eter)

list

In [9]:
np.array([123,"sdaf",False])

array(['123', 'sdaf', 'False'], dtype='<U11')

In [10]:
type(np.array)

builtin_function_or_method

### Why vectorize?
### 1. Much faster
### 2. Easier to read and fewer lines of code
### 3. More closely assembles mathematical notation

### Vectorization is one of the main reasons why NumPy is so powerful.


In [7]:
import numpy as np

a = np.array([[1, 2], [2, 4]])
print(a)

[[1 2]
 [2 4]]


In [8]:
#we must be careful with matrix products!
a = np.array([[1, 2], [2, 4]])
print(a)
print()
b = np.array([[1, 2, 2, 1], [2, 4, 2, 1], [2, 4, 2, 1]])
print(b)
a.dot(b)

[[1 2]
 [2 4]]

[[1 2 2 1]
 [2 4 2 1]
 [2 4 2 1]]


ValueError: shapes (2,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

In [9]:
#we must be careful with matrix products!
a = np.array([[1, 2], [2, 4]])
print(a)
b = np.array([[1, 2, 2, 1], [2, 4, 2, 1], [2, 4, 2, 1]])
print(b)
a.dot(b)

[[1 2]
 [2 4]]
[[1 2 2 1]
 [2 4 2 1]
 [2 4 2 1]]


ValueError: shapes (2,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

In [10]:
print()

In [11]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [12]:
print(np.sum(x))          # Compute sum of all elements; prints "21"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[5 7 9]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[6 15]"

21
[5 7 9]
[ 6 15]


In [14]:
# we start by importing some useful libraries
import pandas as pd #pandas manages our datasets (e.g., csv)
import numpy as np #our friend, numpy

# get two graphic libraries
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
#import the dataset
data_url = 'https://raw.githubusercontent.com/cmdlinetips/data/master/cars.tsv' #we define the url
cars = pd.read_csv(data_url, sep="\t") #pandas allows us to import dataset from url. The rows are separated by the tab. 

# Using the function head() we can see the first 5 rows of the dataset. 
# From the output, we can see that the variable cars is organized as a csv file
cars.head() 

speed  dist
0      4     2
1      4    10
2      7     4
3      7    22
4      8    16