In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np

x = np.array([[1,2,3,4],
            [2,4,5,6,6]])

print(x)
print(type(x))
x

[list([1, 2, 3, 4]) list([2, 4, 5, 6, 6])]
<class 'numpy.ndarray'>


array([list([1, 2, 3, 4]), list([2, 4, 5, 6, 6])], dtype=object)

In [5]:
nd = np.array([x for x in range(56)])

ndarray = nd.reshape((4,2,7))
print(ndarray)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]

 [[42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]]]


In [6]:
ndarray.shape

(4, 2, 7)

In [9]:
ndarray[0:2]

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27]]])

In [14]:
#ndim komutu ile eksen sayısını almış olduk. (number of dimension)
ndarray.ndim

3

In [16]:
#ndarray içindeki toplam eleman sayısı size komutu ile alınır
#benim örneğim için ndarrray hem değişken adım hem de tipi. Burda bahsedilen tabi ki tipidir.
ndarray.size

56

In [18]:
#değişkenimin bellekte ne kadar yer kapladıgını ögrenmek için 
ndarray.itemsize

4

In [19]:
ndarray.dtype

dtype('int32')

In [20]:
import numpy as np    
a = np.arange(72)
a = np.reshape(a, (4,3,2,3))
print(a)
a.shape

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]


 [[[36 37 38]
   [39 40 41]]

  [[42 43 44]
   [45 46 47]]

  [[48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]]

  [[60 61 62]
   [63 64 65]]

  [[66 67 68]
   [69 70 71]]]]


(4, 3, 2, 3)

In [10]:
double = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

intdouble = double.astype("int")

print(intdouble)

[[2 3 1]
 [4 2 1]]


In [11]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
bool_eye = eye.astype("bool")
bool_eye

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [22]:
dizi = np.arange(20)
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
dizi2 = np.arange(20,2)
print(dizi2)

[]


In [31]:
dizi2 = np.arange(1,2,0.2)
dizi2


array([1. , 1.2, 1.4, 1.6, 1.8])

In [32]:
dizi3 = np.arange(0,10,-1)
dizi3

array([], dtype=int32)

In [33]:
my_dizi = np.arange(19)

total = 0
for i in my_dizi:
    total += i
print(total)

171


In [42]:
my_new_dizi = np.arange(1,2,0.2)

total_new = 1
for i in my_new_dizi:
    total_new *= i
print(my_new_dizi)
print(f"Your total result of multiplication from your list is: {total_new}")

[1.  1.2 1.4 1.6 1.8]
Your total result of multiplication from your list is: 4.838399999999999


In [45]:
# 1 ile 10 arasında her ikisini de kapsayacak şekilde sabit elemanlı bir liste oluşturmamızı sağlar
d_new = np.linspace(1,10,5)
d_new

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Numpy üzerinde bazı işlemler

In [46]:
import numpy as np

dizim = np.array([[2,4,6,8],[1,3,5,7,9]])

In [52]:
for elem in dizim:
    print(elem)

[2, 4, 6, 8]
[1, 3, 5, 7, 9]


In [64]:
for elem in dizim:
    if elem[0] % 2 == 1:
        print(elem)
    

[1, 3, 5, 7, 9]


In [68]:
arr_sort = np.array([2,4353,7,77,-5675,34523,234,2,2,45,45,6])
print(np.sort(arr_sort))
arr_sort[0] 
# yukarıdaki sorting işlemini bir degşkene atmadıgım için ana listemde bir degişiklik olmadı

[-5675     2     2     2     6     7    45    45    77   234  4353 34523]


2

In [69]:
### START CODE HERE ### (≈ 1 line of code)
test = "Hello World"
### END CODE HERE ###
print("test: {0}" .format(test))

test: Hello World
